# Generated by Django 4.2.5 on 2023-09-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emprestimo_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(to='app.categoria'),
        ),
    ]
